In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt    
import seaborn as sns
import sklearn

import warnings
warnings.filterwarnings('ignore')

In [2]:
#import data from .csv file
weather = pd.DataFrame(pd.read_csv("Weather Dataset.csv"))
weather.head()

,lat,lon,time,omega_x,omega_y,omega,pr_wtr,rhum_x,rhum_y,rhum,...,tmp_x,tmp_y,tmp,uwnd_x,uwnd_y,uwnd,vwnd_x,vwnd_y,vwnd,rain
0,30.0,70.0,1/1/2015,0.14300,0.10950,0.12600,5.60,1.75,0.75,40.75,...,296.8,282.67500,296.725,4.350000,1.275001,-2.599999,-6.600,-3.925,-3.200000,-9999.0
1,30.0,70.0,1/2/2015,0.02925,0.02450,0.06525,8.40,20.50,19.00,34.50,...,296.8,284.15000,296.700,12.125002,5.850001,-1.749999,-5.075,-3.975,-2.200000,-9999.0
2,30.0,70.0,1/3/2015,0.18125,0.16325,0.10375,11.35,29.50,46.50,41.00,...,296.8,284.67500,296.600,26.575000,10.875000,0.775001,-13.925,-5.725,-0.874999,-9999.0
3,30.0,70.0,1/4/2015,0.12350,0.07725,-0.09000,12.40,36.50,38.75,40.50,...,296.8,285.15002,296.550,35.949997,18.375000,1.325000,-20.400,-6.050,2.925002,-9999.0
4,30.0,70.0,1/5/2015,-0.04575,0.04225,0.01700,11.25,20.75,22.25,38.75,...,296.8,285.75000,296.500,40.700000,17.400002,3.175001,-7.900,-6.550,1.575000,-9999.0

In [3]:
m = len(weather)
m

17902

In [4]:
weather.shape

(17902, 21)

In [5]:
num_vars = ['lat', 'lon','omega_x', 'omega_y', 'omega', 'pr_wtr', 'rhum_x','rhum_y', 'rhum', 'slp', 'tmp_x', 'tmp_y', 'tmp','uwnd_x', 'uwnd_y', 'uwnd', 'vwnd_x', 'vwnd_y', 'vwnd','rain']
data = weather[num_vars]
data

,lat,lon,omega_x,omega_y,omega,pr_wtr,rhum_x,rhum_y,rhum,slp,tmp_x,tmp_y,tmp,uwnd_x,uwnd_y,uwnd,vwnd_x,vwnd_y,vwnd,rain
0,30.0,70.0,0.14300,0.10950,0.12600,5.600000,1.75,0.75,40.75,101852.5,296.8,282.67500,296.72500,4.350000,1.275001,-2.599999,-6.600,-3.925000,-3.200000,-9999.0
1,30.0,70.0,0.02925,0.02450,0.06525,8.400000,20.50,19.00,34.50,101785.0,296.8,284.15000,296.70000,12.125002,5.850001,-1.749999,-5.075,-3.975000,-2.200000,-9999.0
2,30.0,70.0,0.18125,0.16325,0.10375,11.350000,29.50,46.50,41.00,101700.0,296.8,284.67500,296.60000,26.575000,10.875000,0.775001,-13.925,-5.725000,-0.874999,-9999.0
3,30.0,70.0,0.12350,0.07725,-0.09000,12.400000,36.50,38.75,40.50,101795.0,296.8,285.15002,296.55000,35.949997,18.375000,1.325000,-20.400,-6.050000,2.925002,-9999.0
4,30.0,70.0,-0.04575,0.04225,0.01700,11.250000,20.75,22.25,38.75,101620.0,296.8,285.75000,296.50000,40.700000,17.400002,3.175001,-7.900,-6.550000,1.575000,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17897,25.0,77.5,0.07425,0.02250,0.06975,12.425000,28.50,5.75,39.00,101535.0,295.9,291.82500,296.70000,12.975000,1.125001,-3.899998,1.900,-0.899999,-0.699999,0.0
17898,25.0,77.5,-0.05550,-0.00150,0.03375,16.825000,60.50,8.25,54.25,101640.0,295.9,292.12500,296.70000,18.400002,3.850000,-2.249999,7.375,-0.425000,-0.224998,0.0
17899,25.0,77.5,0.18150,0.11825,0.09275,17.575000,12.75,16.25,60.25,101725.0,295.9,292.42500,296.67502,20.525002,5.350001,-1.225000,-2.800,-2.950000,-2.574999,0.0
17900,25.0,77.5,0.07350,0.09025,0.09800,15.424999,14.50,12.00,49.00,101642.5,295.9,292.00000,296.60000,24.275003,10.950001,-0.474999,-1.750,-5.150000,-3.199999,0.0
17901,25.0,77.5,0.05725,0.07875,0.07000,10.700000,6.00,3.00,39.25,101422.5,295.9,290.85000,296.60000,17.200000,8.525002,2.050000,-2.050,-4.800000,-3.124999,0.0

In [6]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()
data[num_vars] = scaler.fit_transform(data[num_vars])
data.head()

,lat,lon,omega_x,omega_y,omega,pr_wtr,rhum_x,rhum_y,rhum,slp,tmp_x,tmp_y,tmp,uwnd_x,uwnd_y,uwnd,vwnd_x,vwnd_y,vwnd,rain
0,1.0,0.0,0.676831,0.785211,0.767720,0.074576,0.0175,0.0075,0.4075,0.794024,0.5625,0.181935,0.449627,0.304140,0.388229,0.368421,0.396447,0.338618,0.311537,0.0
1,1.0,0.0,0.579128,0.718701,0.709531,0.112542,0.2050,0.1900,0.3450,0.776860,0.5625,0.220000,0.447761,0.411969,0.487041,0.397284,0.419501,0.337349,0.356170,0.0
2,1.0,0.0,0.709684,0.827269,0.746408,0.152542,0.2950,0.4650,0.4100,0.755245,0.5625,0.233548,0.440299,0.612371,0.595572,0.483022,0.285714,0.292961,0.415309,0.0
3,1.0,0.0,0.660082,0.759977,0.560824,0.166780,0.3650,0.3875,0.4050,0.779402,0.5625,0.245807,0.436567,0.742390,0.757559,0.501698,0.187831,0.284718,0.584914,0.0
4,1.0,0.0,0.514709,0.732590,0.663314,0.151186,0.2075,0.2225,0.3875,0.734901,0.5625,0.261290,0.432836,0.808266,0.736501,0.564516,0.376795,0.272036,0.524660,0.0

In [7]:
Y = data.pop('rain')
X = data

In [8]:
X.head()

,lat,lon,omega_x,omega_y,omega,pr_wtr,rhum_x,rhum_y,rhum,slp,tmp_x,tmp_y,tmp,uwnd_x,uwnd_y,uwnd,vwnd_x,vwnd_y,vwnd
0,1.0,0.0,0.676831,0.785211,0.767720,0.074576,0.0175,0.0075,0.4075,0.794024,0.5625,0.181935,0.449627,0.304140,0.388229,0.368421,0.396447,0.338618,0.311537
1,1.0,0.0,0.579128,0.718701,0.709531,0.112542,0.2050,0.1900,0.3450,0.776860,0.5625,0.220000,0.447761,0.411969,0.487041,0.397284,0.419501,0.337349,0.356170
2,1.0,0.0,0.709684,0.827269,0.746408,0.152542,0.2950,0.4650,0.4100,0.755245,0.5625,0.233548,0.440299,0.612371,0.595572,0.483022,0.285714,0.292961,0.415309
3,1.0,0.0,0.660082,0.759977,0.560824,0.166780,0.3650,0.3875,0.4050,0.779402,0.5625,0.245807,0.436567,0.742390,0.757559,0.501698,0.187831,0.284718,0.584914
4,1.0,0.0,0.514709,0.732590,0.663314,0.151186,0.2075,0.2225,0.3875,0.734901,0.5625,0.261290,0.432836,0.808266,0.736501,0.564516,0.376795,0.272036,0.524660

In [9]:
Y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: rain, dtype: float64

In [10]:
# Importing Principal Component Analysis

from sklearn.decomposition import PCA
pca = PCA(n_components=19)
principalComponents = pca.fit_transform(X)
principalComponents = pd.DataFrame(principalComponents)
principalComponents

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,-0.266243,-0.791611,-0.219341,-0.044028,-0.337089,-0.345219,0.185630,0.032446,-0.107603,-0.237211,-0.047971,0.098682,0.070869,-0.046865,-0.055095,-0.023618,-0.025553,0.017204,0.019396
1,-0.248866,-0.770432,-0.145512,0.169982,-0.177083,-0.279324,0.105221,0.022027,-0.090141,-0.104541,-0.016765,0.052914,0.099228,-0.011318,0.002158,-0.055120,0.008057,-0.005637,0.006056
2,-0.229803,-0.750413,-0.089091,0.308480,-0.015667,-0.369343,-0.030841,-0.255722,0.005647,-0.008179,0.029248,-0.003221,-0.040828,-0.046090,-0.047888,-0.017624,0.026021,0.024130,-0.016012
3,-0.214522,-0.795318,-0.145684,0.366924,0.032337,-0.262179,-0.010842,-0.291470,0.168673,0.078901,0.225675,-0.121060,0.020519,0.061695,0.009343,-0.029862,-0.023068,-0.002104,-0.064500
4,-0.215406,-0.826230,-0.226670,0.242816,-0.012145,-0.105634,0.107653,-0.252274,0.188154,0.079705,0.050376,-0.048097,0.076588,-0.014729,0.098313,-0.052514,0.102119,-0.024104,-0.043341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17897,0.517984,0.332908,-0.440727,-0.041642,-0.233144,-0.018975,0.002306,0.229643,-0.109077,-0.071249,0.056467,-0.106548,-0.068490,-0.026744,0.000624,0.007264,0.027744,0.054759,0.029661
17898,0.544368,0.389484,-0.367816,0.253215,-0.299806,0.018472,-0.038213,0.294745,0.064332,0.049855,0.042659,-0.096714,-0.075666,0.025587,0.056321,-0.006250,0.084127,0.085454,-0.004750
17899,0.530431,0.362385,-0.424486,-0.073731,-0.257836,-0.073905,-0.001611,-0.099072,-0.012522,-0.115579,-0.040552,-0.070601,-0.134429,0.038884,-0.013057,0.024471,0.017634,0.063020,0.026762
17900,0.551419,0.306164,-0.502716,-0.085671,-0.184377,-0.031864,-0.037801,-0.073672,0.015579,-0.031385,-0.070309,-0.080384,-0.059684,0.027307,0.066485,-0.056166,0.026571,0.037933,0.008161
17901,0.535978,0.284031,-0.541748,-0.225801,-0.162074,-0.022672,0.003903,0.003765,-0.018306,-0.028186,-0.028241,0.019456,0.028516,-0.006505,0.031637,-0.041846,0.016924,0.048907,-0.002649

In [11]:
#Setting the principal components as the input variables

X = principalComponents.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]].values
X

array([[-0.26624331, -0.79161129, -0.21934109, ..., -0.02555263,
         0.01720411,  0.01939569],
       [-0.24886606, -0.7704321 , -0.14551201, ...,  0.00805681,
        -0.00563721,  0.0060559 ],
       [-0.22980255, -0.75041302, -0.08909133, ...,  0.02602126,
         0.02413015, -0.01601219],
       ...,
       [ 0.53043113,  0.36238503, -0.42448557, ...,  0.01763401,
         0.06302027,  0.02676186],
       [ 0.55141883,  0.30616413, -0.50271607, ...,  0.02657062,
         0.03793302,  0.00816112],
       [ 0.53597828,  0.28403071, -0.5417481 , ...,  0.01692408,
         0.04890749, -0.00264869]])

In [12]:
Y = Y.values

print('Y = ', Y[: 5])

Y =  [0. 0. 0. 0. 0.]

In [13]:
#Training and Testing Splitting
np.random.seed(0)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [14]:
# Linear Support vector regression

from sklearn.svm import SVR

svr_lin = SVR(kernel='linear', C=1e2)
svr_lin.fit(X_train, Y_train)
Y_pred = svr_lin.predict(X_test)

In [15]:
# Final loss for linear suport vector regression

errors = np.subtract(Y_pred, Y_test)
sqrErrors = np.square(errors)
m_test = len(X_test)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss

0.04220366299568375

In [16]:
#SVR with rbf kernel

svr_rbf = SVR(kernel='rbf', C=1e-2, gamma=0.1)
svr_rbf.fit(X_train, Y_train)
Y_pred = svr_rbf.predict(X_test)

In [17]:
#Final loss for rbf kernel

errors = np.subtract(Y_pred, Y_test)
sqrErrors = np.square(errors)
m_test = len(X_test)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss

0.042454471780195166

In [ ]:
#SVR with polynomoial kernel

svr_poly = SVR(kernel='poly', C=1e3, degree=2)
svr_poly.fit(X_train, Y_train)
Y_pred = svr_poly.predict(X_test)

In [ ]:
#Final loss for polynomial kernel

errors = np.subtract(Y_pred, Y_test)
sqrErrors = np.square(errors)
m_test = len(X_test)
loss = 1 / (2 * m_test) * np.sum(sqrErrors)
loss